### ISSUE TITLE
Output elemental and nodal results in a dataframe

### ISSUE THREAD

**Issue by sfreund-DLR** [sfreund-DLR/tankoh2#58]
the actual output is limited to angles, hoop shifts and other accumulated data (e.g. mass, length). Create a Dataframe for nodal data and one for elemental data and fill it will all available results.

- elemental (elementalResults.csv)
  - [x] stress
  - [x] strain
  - [x] puck
  - [x] thickness
  - [x] fibre angles
- nodal (nodalResults.csv)
  - [x] mandrel coordinates of liner contour (x,r,l)
  - [ ] coordinates of each layer (x,r,l)

**Comment by jacolinu** [comment]
Fibre angles remain constant within a wound layer right? So all nodes in one layer would have the same fiber angle?

**Comment by sfreund-DLR** [comment]
no, the fibre angle of helical layers at the polar opening is zero and thus varying in the dome section. you can also visualize this in µWind when activating fibre angles
