### ISSUE TITLE
Check mass balance output

### ISSUE THREAD

**Issue by mvinot** [sfreund-DLR/tankoh2#65]
Check if the mass balance is correct. For different configurations, the TotalMass and InsulationMass seem not to be correctly exported from createDesignWinding and getLinearResults (in control_winding).

**Comment by sfreund-DLR** [comment]
could you please provide your input to check this? It used to be an issue in recent days but might be fine with recent commits.

**Comment by sfreund-DLR** [comment]
This input is an example for the problem:

 = OrderedDict([
    ('tankname', 'NGT-BIT-2022-03-04'),
    ('pressure', 70), # MPa
    ('burstPressure', 140.), # MPa
    ('valveReleaseFactor', 1.),
    # Geometry
    ('polarOpeningRadius', 23),
    ('dcyl', 422.),
    ('lcyl', 500.),
    # design philosophy
    ('safetyFactor', 2.0),
    ('failureMode', 'fibreFailure'),
    # material
    ('materialName', 'CFRP_T700SC_LY556'),
    # fibre roving parameter
    # single ply thickness with 62% FVG
    ('layerThkHoop', 0.089605735), # thickness for 62% FVG
    ('layerThkHelical', 0.089605735), # thickness for 62% FVG
    # single ply thickness with 55% FVG
    #('layerThkHoop', 0.101010101), # thickness for 55% FVG
    #('layerThkHelical', 0.101010101), # thickness for 55% FVG
    # single ply thickness with 60% FVG
    #('layerThkHoop', 0.092592593), # thickness for 60% FVG
    #('layerThkHelical', 0.092592593), # thickness for 60% FVG
    ('rovingWidth', 8.00),
    ('numberOfRovings', 6), # number of spools usabale at INVENT
    ('tex', 800),
    ('fibreDensity', 1.8),
    # optimizer settings
    ('maxlayers', 3),
    ('verbose', False),
    ])

**Comment by sfreund-DLR** [comment]
solved with e6cd17204f694255c5820d168f0fa0cd7c1786a3
