### ISSUE TITLE
additional output

### ISSUE THREAD

**Issue by sfreund-DLR** [sfreund-DLR/tankoh2#68]
- [x] add gravimetric index
- [x] add stress ratio helicalfibres/hoopfibres in cylindrical section (use helical fibre with lowest angle, first element)

**Comment by jacolinu** [comment]
Nebenbei: funktion ParseDesginArgs zu ParseDesignArgs umbenennen?

**Comment by jacolinu** [comment]
gravimetric index requires mass as input which is converted to volume (new issue?)

**Comment by sfreund-DLR** [comment]
> Nebenbei: funktion ParseDesginArgs zu ParseDesignArgs umbenennen? Ebenso "insultaion mass"

yes, always ;-)

**Comment by sfreund-DLR** [comment]
> gravimetric index requires mass as input which is converted to volume (new issue?)

yes

**Comment by jacolinu** [comment]
closed with [6186cb8](https://github.com/sfreund-DLR/tankoh2/commit/6186cb866f659bfa5c51c657426f56bcc00ca41c)
