### ISSUE TITLE
output cylindrical and dome thickness

### ISSUE THREAD

**Issue by sfreund-DLR** [sfreund-DLR/tankoh2#71]
output cylindrical and dome thickness for outer shape calculations

**Comment by jacolinu** [comment]
my first idea for the dome thickness was to simply output the maximum thickness as a conservative value when sizing the length of the tank. The more correct solution would need to know the angle at different points on the dome, and then compare the x part of the thickness along the contour to find the maximum x- thickness. (Or maybe use the x-coordinates of the nodes in the plies, if available )

**Comment by sfreund-DLR** [comment]
> my first idea for the dome thickness was to simply output the maximum thickness as a conservative value 
is fine for me
